### ISSUE TITLE
# 개발 진행 (2017-11-11) Meeting progress

### ISSUE THREAD

**Issue by muf** [muf/KHU-2017-2-DesignD#30]
##  TODOs
- UI 구성 및 컴포넌트 연결
- 게임 쪽 모델링
- 계약 쪽 모델링

## 작업 내용 (황진하)
- [ ] 경기 관련 플로우 디자인 및 프레임 개발 (1h)
- [ ] 계약 관련 플로우 디자인 및 프레임 개발 (1h)
- [ ] Validation Handling (30m)
- [ ] UI / UX 디자인 체크 (미정)
### 추가 작업 (황진하)
- [x] 졸연 KHU-HUB 제출

##  [#progress](https://github.com/muf/KHU-2017-2-DesignD/issues/32)
- [x] 검색 개발 진행 (1h) [1h]
- [x] 계약 구조 설계 및 컴포넌트 개발 / 테스트 (1h) [2h]
- [ ] 계약 모델링 완료 (1h)
### 연장된 작업 내용
- [ ] 게임 데이터 생성 및 컴포넌트 개발 / 테스트 (1h 30h)
- [ ] 게임 모델링 완료 (1h)

### 추가 작업 (박정현)
- [x] 이슈 및 문서 정리 작업 진행 (30m) [15m]

## 작업 시간 
- 09 : 00 ~ 14: 00 ( 4h )

## 참여자
- 박정현, 황진하

**Comment by muf** [comment]
## 버그 이슈
- https://github.com/muf/KHU-2017-2-DesignD/issues/29 (황진하 담당)
- [x] 확인

### 제보자
- 박정현

**Comment by muf** [comment]
## 제안 수정 사항
- DB primary key naming 다시 하기
```
ex)  cid => contractId, cid => clubId
```
- [x] 확인
### 제안자
- 박정현

**Comment by muf** [comment]
## 제안 수정 사항 (완료)
- 내용 링크(https://github.com/muf/KHU-2017-2-DesignD/issues/33)
- [x] 확인

### 제안자
- 황진하
