### ISSUE TITLE
# 개발 진행 (2017-11-11)  박정현

### ISSUE THREAD

**Issue by muf** [muf/KHU-2017-2-DesignD#32]
## 작업 내용 (박정현) (4h 30m) [4h + (2h 30m)]
- [x] 검색 개발 진행 (1h) [1h]
- [x] 계약 구조 설계 및 컴포넌트 개발 / 테스트 (1h) [2h]
- [ ] 계약 모델링 완료 (1h)

## 연장된 작업 내용
- [ ] 게임 데이터 생성 및 컴포넌트 개발 / 테스트 (1h 30h)
- [ ] 게임 모델링 완료 (1h)

### 추가 작업 (박정현)
- [x] 이슈 및 문서 정리 작업 진행 (30m) [15m]

## 작업 시간
- 09 : 00 ~ 14:00 (4h)

**Comment by muf** [comment]
## 계약 구조 설계 및 컴포넌트 개발 / 테스트 (1h) [2h]
- retrieve(string keyword) 말고 retrieve(int uid)도 따로 구성.
- uid input으로 넣은 이유는 매번 새창으로 세부 정보를 볼때 업데이트된 정보로 볼 수 있도록 하기 위함이고, 또한 playerId나 clubId를 uid 기반으로 가져올 수 있게 하기 위해 추가했음
- 임시로 바로 계약 되도록 구성. (게임 모델 추가를 위한 테스트 데이터 구성)
- 로그인시 client type을 알 수가 없어서  client type도 알 수 있도록 localdata 수정 요청 -> 수정 완료
- 이 과정에서 `getAccountData`라는 걸 만들어서 uid를 주면 거기에 맞는 계정 객체를 자동으로 찾아서 반환하는 함수도 추가하였음. 기존 코드는 그대로 사용하고, uid로 사용자를 처음부터 알아내야 하는 경우에는 이 함수를 사용하면 됨.
- localdata `clientType` 에서 `userType`으로 통합. (https://github.com/muf/KHU-2017-2-DesignD/issues/33 , 32e4df2)
- contract table에서 pid, cid 사용할 경우 uid로 매번 타입을 다시 알아내야 하는 불편함이 존재. 그래서 그냥 uid로 모두 대체. `playerUserId` 와 `clubUserId`로 변경하였음

**Comment by muf** [comment]
## TODos
### 로그인 창
- [ ] 로그인 창 password 스타일 변경
- [ ] 로그인  창 엔터 적용
- [ ] 로그인 창 비어있을 경우 ` null error ` -> 문장으로 입력
- [ ]  한글패치 ㄱㄱ

### 회원가입 창
- [ ] 이메일 형식 검사
- [ ] 패스워드 창 크기 조절 (수직-센터)
- [ ] 이름 다 trim으로 공백 제거 + 비었는지 검사 후 알람
- [ ] Birth 입력을 다운 리스트 박스 3개로 년/월/일 받고. 저장할떄는 int로 변환해서 저장하도록 수정
- [ ] 무게 값 제한 검사.. 정수형으로 변환해서 0~500 사이 예를들면 
- [ ] 키는 m로 정하고, 값 사이는 0~500 사이 예를들면
- [ ]  회원가입 성공 하고 알림 후 꺼지도록.
- [ ] 맨 밑에 불필요한 레지스터 버튼 없애고. 가운데 페이지 정렬
- [ ] 폼 사이 마진좀 줘서 이쁘게 

### 왼쪽 바
- [ ]  센터 ㄴㄴ
- [ ] 안보일떄는 자리 차지 ㄴㄴ

### 탑 패널
- [ ] 옵션 ㄴㄴ 내정보
- [ ] 로그인 했을때 회원가입 버튼 ㄴㄴ 아니면 로그인 창에서 다시 새로운 창으로 회원가입
- [ ] 로그인 했을 때 안했을 때 보이고 안보이고 잘 하셈

### 내정보 이쁘게 데이터 활용해서
- http://elkane.tistory.com/61
